### ISSUE TITLE
close large images by clicking on it

### ISSUE THREAD

**Issue by eesur** [Hejtmus/svelte-lightbox#18]
thanks for this component, so useful—I'm testing it out: [https://eesur.github.io/akaal/ ](https://eesur.github.io/akaal/)

but when I click on the thumbnail image to view the large image I have to click outside of the image or the 'x' to close it
is it possible to click on the image and close it? (then I could lose the 'x') and be easier to navigate (I'm not using the gallery view)

thanks for any pointers :)

**Comment by Hejtmus** [comment]
# Hey

Thanks for your appreciation. 

Today I started working on refactoring and reworking CSS of this component to fix issue #9 and #11. 
Also I can implement feature you suggest. Probably it will be optional feature you can enable by setting boolean prop.

Hopefully I can make it until tomorrow.

Have a nice day.

**Comment by Hejtmus** [comment]
# Done

Hi @eesur, feature you proposed has been implemented in version 0.3.0, already published on NPM.

For enabling that feature you need to set `<Lightbox>` props clickToClose and closeButton to true.
You can find this in [documentation](https://github.com/Hejtmus/svelte-lightbox#clicktoclose-boolean).

Please let me know this did the trick, if not, I can give it another try.

Thank you for your contribution with idea.

**Comment by eesur** [comment]
@Hejtmus thank you so much—I will test out later today and let you know

**Comment by eesur** [comment]
@Hejtmus  works great! — much appreciated and thanks again for the speedy refactoring and all the hard work

**Comment by Hejtmus** [comment]
I love to read that,

thank you for your response, but mainly for suggesting this feature. I'm glad to see that the open source model works :D.

Best regards.
