### ISSUE TITLE
Allow for multiple gallery thumnails

### ISSUE THREAD

**Issue by lalilaloe** [Hejtmus/svelte-lightbox#37]
The gallery function expects one thumbnail. Multiple thumbnails are not possible.

Right now i'm using multiple lightboxes to work around this issue, but it would be nice if implemented so that you can display a gallery and click on a image to enlarge it into Lightbox and keep browsing in the gallery.

This is a costly workaround if you have a lot of pictures in a gallery

```
<Carousel>
      {#each images as image, key}
            <Lightbox noScroll={false} transitionDuration={200} {gallery}>
              <LightboxGallery galleryArrowsCharacter="loop">
                            {#each images as galleryImage, index}
                                {#if index !== key}
                                    <LightboxImage>
                                      <img src={galleryImage.image.mediaItemUrl} alt={galleryImage.image.altText}/>
                                    </LightboxImage>
                                {/if}                                
                            {/each}
                </LightboxGallery>
                <img slot="thumbnail" src={image.image.mediaItemUrl} alt={image.image.altText} />
            </Lightbox>
      {/each}
    </Carousel>
```

My suggestion is to allow multiple thumbnails, using a config like this

 https://github.com/Hejtmus/svelte-lightbox/blob/3b0e5936ca13c47b27c95d86bb643eae70d32b3d/src/Lightbox.svelte#L15
add
```suggestion
export let galleryThumbnails = false;
```
https://github.com/Hejtmus/svelte-lightbox/blob/3b0e5936ca13c47b27c95d86bb643eae70d32b3d/src/Lightbox.svelte#L79
```suggestion
{#if thumbnail || gallery && !galleryThumbnails}
```

But then i run into problems like `Uncaught (in promise) TypeError: can't access property "insertBefore", target is null`

**Comment by Hejtmus** [comment]
Hi,

after long planing, I've decided to entirely rework gallery logic. Current implementation of gallery is messy and unsustainable (I was about to implement your suggestion, but actually I couldn't). New implementation will allow gallery to have multiple thumbnails and a lot of more features, and also it will be a lot of cleaner solution. Actually rework of gallery will be so drastic, that I'll be releasing it under vesion `1.0.0`.

Best regards,
Filip.

**Comment by Hejtmus** [comment]
Done,

this feature has been implemented. It will be shipped within new release, which appears to be 1.0.0, I think it'll be out next week.
Sorry for late implementation, but I didn't have enough time, now I have.

Filip.
