### ISSUE TITLE
Missing basic CSS classes to easily modify lightbox style

### ISSUE THREAD

**Issue by luukio** [Hejtmus/svelte-lightbox#60]
Currently it seems only CSS classes `svelte-lightbox-thumbnail ` and `svelte-lightbox-body` are available to customise. 

Without having to traverse in CSS, it would be easier to give elements like the close button and background overlay a fixed class instead.

**Comment by Hejtmus** [comment]
Hey,

## Current solution

Customization of individual parts of lightbox is done by specifying desired props of particular elements by providing `<Lightbox>`  component with [`customization` object](https://github.com/Hejtmus/svelte-lightbox/blob/87e5225587d8a5afd3fb799fa067cd7038943bce/src/lib/Types.ts#L4). 
You are right that there is no way of customization of background overlay, so I will open separate issue and add it to customization object.

### Sample pseudo-code

```
<script>
    ...
    const lightboxCustomization = {
        closeButtonProps: {
            class: '...',
            style: '...'
        }
    }
    ...
<script/>

<Lightbox ... customization={lightboxCustomization}>
...
</Lightbox>
```

## Fixed css classes

If I understand you right, you propose adding global classes to every part of lightbox, which can be later styled by user.  So customization could by done just by defining those CSS classes.

**Comment by luukio** [comment]
Thanks, didn't realise it had prop customization! The `lightboxCustomization` helps, but I'd still need to add that to every single instance of the `Lightbox` right? 

And yes global classes would be helpful, it would make it a bit less redundant? There might be other options!

**Comment by luukio** [comment]
Guess you could do something like

**LightboxHeader.svelte**
```
<div class="svelte-lightbox-header" class:fullscreen={imagePreset === 'fullscreen'} {...$$restProps}>
    ...
</div>

<style>
    div.svelte-lightbox-header {
        ...
    }
    div.svelte-lightbox-header.fullscreen {
        ...
    }
</style>
```

**Comment by Hejtmus** [comment]
Yes, customization object has to be set individually to single instances of `<Lightbox>`, which makes styling inconvenient. I like your proposed solution, although there are other options, but I think using global classes is the most elegant one. It should be easy to implement, but I'm busy until Sunday. If you want, you can make PR, I will look at it, merge it and release it sooner. If you would make PR, I would appreciate updating documentation.

**Comment by Hejtmus** [comment]
Thank you @luukio  for PR, I already published new minor version to npm.

**Comment by luukio** [comment]
No problem, sorry I am not that active on GitHub. :)
