### ISSUE TITLE
500 Internal server error!

### ISSUE THREAD

**Issue by amr3k** [Hejtmus/svelte-lightbox#62]
Neither [docs](https://svelte-lightbox.js.org/docs) or [examples](https://svelte-lightbox.js.org/examples) links work!

![image](https://user-images.githubusercontent.com/12211826/203702127-3af4d4b9-bcec-4ab8-a8c1-c7eca3b80f43.png)

**Comment by Hejtmus** [comment]
Hello, 

thank you for reporting this, I'm quite busy, but I will look at it.

Best regards,
Filip.

**Comment by Hejtmus** [comment]
Hey @amr3k,

I have found the bug and fixed it. Please check it, if the error 500 persists, please reopen this issue.
