### ISSUE TITLE
Description is insided of image

### ISSUE THREAD

**Issue by Lumca** [Hejtmus/svelte-lightbox#9]
Hello,

thank you for this lib, it works nicely.
There is one bug I have found.
Only when the image is almost over all window than the description text is inside of the image.

Just letting you know.

Lumír

**Comment by Hejtmus** [comment]
### Hi,

**thank you** for reporting this bug. Fix for this bug will be out in few weeks (or sooner), because currently I am too busy. I'll do my best to release it **ASAP**.

For now, this bug can be **prevented** using style property in img element.

**Filip Holčík**

**Comment by Hejtmus** [comment]
# Resolved

Hello @Lumca, sorry for delay, but I was too busy. 
I added image preset feature, which solves this problem and 1 more that I discovered during my attempt to replicate your bug.

If you can't give me response, I will understand it.

A keďže si rozumieme aj po našich rodných jazykoch, tak ti ďakujem po Slovensky :D.
